# 正式网环境-阿里云

# 系统配置
app:
    config:
        uploadPath: c:\\boms\\upfiles
    info:
        download-pre: crm.zzbage.com/upfiles/

# spring相关配置
spring:
    # 数据源配置
    datasource:
        url: jdbc:mysql://rm-wz9462081iw1lz598.mysql.rds.aliyuncs.com:3306/boms?zeroDateTimeBehavior=convertToNull&relaxAutoCommit=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: boms
        password: Boms1234
        driver-class-name: com.mysql.jdbc.Driver

# 服务器
server:
    #端口
    port: 8080
